name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Install ubuntu cmake
      run: |
        sudo apt update
        sudo apt install cmake

    - name: Setup vapoursynth
      uses: deadnews/action-setup-vs@v1.0.4

    - name: Build AviSynth/VapourSynth plugin
      run: |
        pushd FFmpeg
        ./configure --enable-gpl --enable-version3 --disable-static --enable-shared --disable-all --disable-autodetect --enable-avcodec --enable-avformat --enable-swresample --enable-swscale --disable-asm --disable-debug
        make -j2
        sudo make install -j2
        popd
        cmake_settings=(-S . -G Ninja -DENABLE_DAV1D=OFF -DENABLE_MFX=OFF -DENABLE_XML2=OFF -DENABLE_VPX=OFF -DENABLE_VULKAN=OFF -DZLIB_USE_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON)
        cmake -B build_vs -DBUILD_AVS_PLUGIN=OFF "${cmake_settings[@]}"
        cmake --build build_vs -j 2

    - name: Zip the Build
      run: zip -r release.zip "build_vs"
    
    - name: artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: release.zip
