name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Install cmake
      uses: lukka/get-cmake@v4.1.0-rc1

    - name: Setup vapoursynth
      uses: deadnews/action-setup-vs@v1.0.3

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        cache: true

    - name: Clone libdav1d
      run: |
        git clone --depth=1 https://code.videolan.org/videolan/dav1d.git
        cd dav1d
        
    - name: Build libdav1d
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: install
        directory: build
        setup-options: --default-library=static

    - name: Build FFmpeg
      run: |
        pushd FFmpeg
        ./configure --enable-gpl --enable-version3 --disable-static --enable-shared --disable-all --disable-autodetect --enable-libdav1d --enable-avcodec --enable-avformat --enable-swresample --enable-swscale --disable-asm --disable-debug
        make -j8
        sudo make install -j8
        mkdir build
        make install -j8 DESTDIR=build
        popd

    - name: Build  AviSynth/VapourSynth plugin
      run: |
        cmake_settings=(-S . -G Ninja -DENABLE_DAV1D=ON -DENABLE_MFX=OFF -DENABLE_XML2=OFF -DENABLE_VPX=OFF -DENABLE_VULKAN=ON -DZLIB_USE_STATIC_LIBS=OFF -Ddav1d_USE_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF)
        cmake -B build_vs -DBUILD_AVS_PLUGIN=OFF "${cmake_settings[@]}"
        cmake --build build_vs -j 16

    - name: upload libdav1d build
      uses: actions/upload-artifact@v4.6.2
      with:
        name: libdav1dbuild
        path: dav1d/build

    - name: upload ffmpeg build
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ffmpegbuild
        path: FFmpeg/build
    
    - name: upload vsplugin build
      uses: actions/upload-artifact@v4.6.2
      with:
        name: vsplugin
        path: build_vs
